[package]
name = "rust_commandline_template"
version = "0.1.0"
authors = ["wtetsu <tewatana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.6", features = ["process"] }
futures = "0.3.1"
